import Icon from '../components/ui/Icon'
import { Button, Card, SectionTitle, StatTile, StatusBadge, cx } from '../components/ui/primitives'
import RoomCard from '../components/RoomCard'
import { useHome } from '../context/HomeContext'
import { ROOMS } from '../data/rooms'
import { DEVICE_CATALOG } from '../data/devices'
import { temp, watts, round } from '../utils/format'

export default function Rooms() {
  const { state, api, power } = useHome()
  const rooms = state.sensors.rooms

  const occupied = ROOMS.filter((r) => rooms[r.id].motion)
  const avgTemp = ROOMS.reduce((a, r) => a + rooms[r.id].temp, 0) / ROOMS.length
  const lightsOn = DEVICE_CATALOG.filter((d) => d.category === 'lights' && state.devices[d.id]?.on).length
  const warmest = ROOMS.reduce((a, r) => (rooms[r.id].temp > rooms[a.id].temp ? r : a), ROOMS[0])

  return (
    <div className="space-y-6 animate-float-in">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile
          icon="Sofa"
          tone="emerald"
          label="Rooms monitored"
          value={ROOMS.length}
          hint={`${DEVICE_CATALOG.length} connected devices`}
        />
        <StatTile
          icon="Radar"
          tone={occupied.length ? 'emerald' : 'slate'}
          label="Occupied now"
          value={occupied.length}
          hint={occupied.length ? occupied.map((r) => r.name).join(', ') : 'Nobody detected anywhere'}
        />
        <StatTile
          icon="Thermometer"
          tone={avgTemp > state.prefs.tempMax ? 'amber' : 'sky'}
          label="Average temperature"
          value={round(avgTemp, 1)}
          unit="°C"
          hint={`Warmest ${warmest.name} at ${temp(rooms[warmest.id].temp)}`}
        />
        <StatTile
          icon="Lightbulb"
          tone={lightsOn ? 'amber' : 'slate'}
          label="Lights on"
          value={lightsOn}
          hint={`Household draw ${watts(power.total)}`}
        />
      </div>

      {/* quick actions */}
      <Card className="flex flex-wrap items-center gap-2.5 p-4">
        <div className="mr-auto flex items-center gap-2">
          <Icon name="SlidersHorizontal" size={15} className="text-mist-400" />
          <span className="text-[12.5px] font-medium text-mist-200">Whole-home actions</span>
        </div>
        <Button
          variant="ghost"
          size="sm"
          icon="Lightbulb"
          onClick={() => api.run({ type: 'ALL_LIGHTS_OFF' }, 'manual', 'All lights switched off')}
        >
          All lights off
        </Button>
        <Button
          variant="ghost"
          size="sm"
          icon="AirVent"
          onClick={() => api.run({ type: 'ALL_CLIMATE_OFF' }, 'manual', 'Climate devices switched off')}
        >
          Climate off
        </Button>
        <Button
          variant="primary"
          size="sm"
          icon="Leaf"
          onClick={() => api.run({ type: 'ECO_SWEEP' }, 'manual', 'Eco sweep complete')}
        >
          Eco sweep
        </Button>
      </Card>

      <section>
        <SectionTitle icon="Sofa" hint="tap any control — the change propagates everywhere instantly">
          Room control
        </SectionTitle>
        <div className="grid gap-4 xl:grid-cols-2">
          {ROOMS.map((room) => (
            <RoomCard key={room.id} room={room} />
          ))}
        </div>
      </section>

      {/* presence simulator */}
      <section>
        <SectionTitle icon="Radar" hint="no physical PIR sensors — these drive the simulation model">
          Presence simulator
        </SectionTitle>
        <Card className="p-4">
          <p className="mb-3 text-[12px] leading-relaxed text-mist-400">
            Occupancy is generated by a per-room Markov chain weighted by the current home mode. Use these to
            force a state and watch the automations and AI recommendations react.
          </p>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {ROOMS.map((room) => {
              const s = rooms[room.id]
              return (
                <div key={room.id} className="rounded-xl bg-white/4 p-3 ring-1 ring-white/6">
                  <div className="flex items-center justify-between">
                    <span className="text-[12px] font-medium text-mist-100">{room.name}</span>
                    <StatusBadge tone={s.motion ? 'emerald' : 'slate'} size="sm" pulse={s.motion}>
                      {s.motion ? 'Motion' : 'Empty'}
                    </StatusBadge>
                  </div>
                  <div className="mt-2.5 flex gap-1.5">
                    <button
                      type="button"
                      onClick={() => api.simulate('motion_detected', { room: room.id })}
                      className={cx(
                        'flex-1 rounded-lg px-2 py-1.5 text-[11px] font-medium transition',
                        'bg-emerald-500/12 text-emerald-300 ring-1 ring-emerald-400/25 hover:bg-emerald-500/20',
                      )}
                    >
                      Detect motion
                    </button>
                    <button
                      type="button"
                      onClick={() => api.simulate('motion_stop', { room: room.id, minutesAgo: 24 })}
                      className="flex-1 rounded-lg bg-white/6 px-2 py-1.5 text-[11px] font-medium text-mist-300 ring-1 ring-white/10 transition hover:bg-white/12"
                    >
                      Mark empty
                    </button>
                  </div>
                </div>
              )
            })}
          </div>
        </Card>
      </section>
    </div>
  )
}
